### ISSUE TITLE
TransactionalIndexedCollection.update don't work with UniqueIndex

### ISSUE THREAD

**Issue by vlastimil-dolejs** [npgall/cqengine#90] opened 2016-09-16 14:41 UTC
I have `TransactionalIndexedCollection` with `UniqueIndex` on primary key. When I try to `update` object in the collection with another object that has the same primary key, but different state, the `UniqueConstraintViolatedException` is thrown.
This is due to order of add/remove operations inside of update method. It should remove the objects first and then add new objects. This problem is specific to `TransactionalIndexedCollection`. Default implementation `ConcurrentIndexedCollection` use right order of operations.

Example:
```groovy
IndexedCollection<Person> cqengine = new TransactionalIndexedCollection<>(Person.class)
cqengine.addIndex(UniqueIndex.onAttribute(Person.ID_ATTRIBUTE))
def person = new Person(id: 1, name: "Boob")
cqengine.add(person)
def updatedPerson = new Person(id: 1, name: "Bob")
cqengine.update([person], [updatedPerson])
// thrown UniqueConstraintViolatedException
```

**Comment by npgall** [comment] 2016-09-16 18:58
Hi Vlastimil,

This is a duplicate of issue #67 actually.

For CQEngine 2.7.1 I updated the JavaDocs of UniqueIndex to document this
behavior - although I have not published the updated JavaDocs to the site
yet. But if you view the JavaDoc of UniqueIndex in your IDE you should see
it.

Basically instead you need to use:  HashIndex.onSemiUniqueAttribute()

You can find a discussion about this in the other issue.

Hope that helps!
Niall

**Closed** 2016-09-18 23:40 UTC

**Comment by vlastimil-dolejs** [comment] 2016-09-19 07:29
Thank you - now I understand.
Vlastimil
