### ISSUE TITLE
java.lang.IllegalStateException: Unable to bulk add rows to the index table: UnnamedattributeclassreproduceCategory1. Rolled back: true

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#135] opened 2017-04-26 16:08 UTC
**Main**:
```
package reproduce;

import com.googlecode.cqengine.ConcurrentIndexedCollection;
import com.googlecode.cqengine.IndexedCollection;
import com.googlecode.cqengine.index.navigable.NavigableIndex;
import com.googlecode.cqengine.persistence.disk.DiskPersistence;
import java.io.File;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FaultyAdder {

    public static void main(String args[]) {
        IndexedCollection<Category> categories;
        categories = new ConcurrentIndexedCollection<>(DiskPersistence.onPrimaryKeyInFile(Category.ID_INDEX, new File("categories.dat")));
        categories.addIndex(NavigableIndex.onAttribute(Category.ID_INDEX));
        categories.addIndex(NavigableIndex.onAttribute(Category.NAME_INDEX));
        if (categories.isEmpty()) {
            try {
                categories.add(new Category("Pop"));
                categories.add(new Category("Rock"));
                categories.add(new Category("Hip Hop"));
            } catch (Exception ex) {
                Logger.getLogger(FaultyAdder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(Arrays.toString(categories.toArray()));
    }
}
```

**Bean**:
```
package reproduce;

import com.googlecode.cqengine.attribute.SimpleAttribute;
import com.googlecode.cqengine.query.option.QueryOptions;
import java.io.Serializable;
import java.util.UUID;

public class Category implements Serializable {

    public final String id;
    public final String name;

    public Category(final String name) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
    }

    public static final SimpleAttribute<Category, String> ID_INDEX = new SimpleAttribute<Category, String>() {
        @Override
        public String getValue(Category category, QueryOptions queryOptions) {
            return category.id;
        }
    };

    public static final SimpleAttribute<Category, String> NAME_INDEX = new SimpleAttribute<Category, String>() {
        @Override
        public String getValue(Category category, QueryOptions queryOptions) {
            return category.name;
        }
    };

}
```

**Stack**:
```
SEVERE: null
java.lang.IllegalStateException: Unable to bulk add rows to the index table: UnnamedattributeclassreproduceCategory1. Rolled back: true
	at com.googlecode.cqengine.index.sqlite.support.DBQueries.bulkAdd(DBQueries.java:305)
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex.addAll(SQLiteIndex.java:452)
	at com.googlecode.cqengine.index.sqlite.SQLiteIdentityIndex.addAll(SQLiteIdentityIndex.java:115)
	at com.googlecode.cqengine.persistence.support.sqlite.SQLiteObjectStore.add(SQLiteObjectStore.java:106)
	at com.googlecode.cqengine.ConcurrentIndexedCollection.add(ConcurrentIndexedCollection.java:350)
	at reproduce.FaultyAdder.main(FaultyAdder.java:21)
```

**Comment by npgall** [comment] 2017-04-27 13:35
Can you provide the "Caused by" exception(s)? There is an exception chain, and only the top one is included above.

If you could supply attribute names to the attribute constructors, it would simplify troubleshooting too, as the names of attributes will be included in exception messages.

**Comment by bluedoo** [comment] 2017-04-27 14:03
@npgall I've figured out the issue. This occurs with JDK9 only, when you run with JDK8 it doesn't happen anymore. I couldn't tell you why though.

Could you possibly provide a response to the older/easier issues? I think they'll be quick to answer (Sorry to ask here)

**Comment by npgall** [comment] 2017-04-27 20:09
Okay no problem. When JDK 9 is released we can make sure CQEngine is compatible, but not before then :)

Regarding the other issues, I will be quite busy for the next couple of weeks. Hopefully in a few weeks I will have more time to look at those!

**Closed by npgall** 2017-04-27 20:09 UTC
