### ISSUE TITLE
Remove from TransactionalIndexedCollection hangs indefinitely

### ISSUE THREAD

**Issue by ashmishr** [npgall/cqengine#263] opened 2020-02-08 21:49 UTC
Hi Niall,

This is a great project. I was trying to use raw sqllite however cqengine has much better api and features.

I came across a quite strange problem:
TransactionalIndexedCollection hangs indefinitely when trying to remove items.

I used the Car class: cqengine/code/src/test/java/com/googlecode/cqengine/testutil/Car.java
with additional attribute version = VERSION_GENERATOR.incrementAndGet();
as suggested and modified equals.

```
      @Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (!(o instanceof Car))
			return false;
		Car car = (Car) o;
		if (carId != car.carId)
			return false;
		if (this.version != car.version)
			return false;
		return true;
	}
	@Override
	public int hashCode() {
		return carId;
	}
```

The test code is trivial : 
```
        public static void main(String[] args) {
		TransactionalIndexedCollection<Car> cache = new TransactionalIndexedCollection<>(Car.class);

		cache.addIndex(NavigableIndex.onAttribute(Car.CAR_ID)); // SimpleAttribute
		cache.addIndex(ReversedRadixTreeIndex.onAttribute(Car.MANUFACTURER));
		cache.addIndex(SuffixTreeIndex.onAttribute(Car.MODEL));
		cache.addIndex(HashIndex.onAttribute(Car.FEATURES)); // MultiValueAttribute (features: List<String>)

		// new Car(int carId, String manufacturer, String model, Color color, int doors,
		// double price, List<String> features, List<String> keywords)
		Car car1 = new Car(1, "FORD", "ford focus", Car.Color.BLACK, 2, 10000.00d,
				Arrays.asList("spare tyre", "sunroof"), Arrays.asList("great condition, low mileage"));
		cache.add(car1);
		cache.add(new Car(2, "FORD", "ford taurus", Car.Color.BLUE, 4, 40000d, Arrays.asList("spare tyre", "radio"),
				Arrays.asList("dirty and unreliable, flat tyre")));
		cache.add(new Car(3, "HONDA", "honda civic", Car.Color.RED, 4, 10100d, Arrays.asList("radio"),
				Arrays.asList("has a flat tyre and high mileage")));
                System.out.println("Removing car with same attribs different (atomic) version");
		boolean removed = cache.remove(new Car(1, "FORD", "ford focus", Car.Color.BLACK, 2, 10000.00d,
				Arrays.asList("spare tyre", "sunroof"), Arrays.asList("great condition, low mileage")));
		System.out.println("Removed :" + removed);

		System.out.println("Removing with reference of original car1");
		cache.remove(car1);
		System.out.println("Removed :" + removed);

	}
````

Execution always hangs on remove statement. I tried it a few times to be sure. Here's the thread dump.
Tried with openjdk-11.0.6.10 (from RedHat) , cqengine-2.12.4 and 3.4.0

```
 "main" #1 prio=5 os_prio=0 cpu=531.25ms elapsed=25.59s tid=0x00000254dcb1d800 nid=0x6f28 waiting on condition  [0x000000e301ffe000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.6/Native Method)
	- parking to wait for  <0x000000061f74e2c0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.6/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.6/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.6/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.6/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(java.base@11.0.6/ReentrantReadWriteLock.java:959)
	at com.googlecode.cqengine.TransactionalIndexedCollection.incrementVersion(TransactionalIndexedCollection.java:161)
	at com.googlecode.cqengine.TransactionalIndexedCollection.update(TransactionalIndexedCollection.java:259)
	- locked <0x000000061f74e250> (a java.lang.Object)
	at com.googlecode.cqengine.TransactionalIndexedCollection.update(TransactionalIndexedCollection.java:185)
	at com.googlecode.cqengine.TransactionalIndexedCollection.remove(TransactionalIndexedCollection.java:286)
	at com.xyz.CQEngineCacheTest.remove(CQEngineCache.java:45)
	at com.xyz.main(CQEngineCacheTest.java:24) 
```

Could you please confirm if its a known issue and investigate? 
Please let me know if I am trying to use it wrongly.

**Comment by npgall** [comment] 2020-03-27 00:36
Hi Ashish,

Sorry for my delay replying.

I was not able to reproduce the problem actually. That main method seems to execute correctly for me. It doesn't hang, it completes normally, and it prints "Removed: true" at the end. I've tested with OpenJDK 1.8.0_151 and OpenJDK 11.0.3 on MacOS Mojave.

So I guess there must be something different between our machines/environments, or some discrepancy between the test cases we are running.

Usually it's best to reduce a test case to the minimal circumstances that will reproduce the problem. In your code, I see you are adding various indexes. Are those actually necessary to reproduce the problem? Including any complexity which is not needed to reproduce the problem makes it more difficult and time consuming to troubleshoot.

Could you provide a [minimal test case](http://sscce.org/) that will reproduce the issue on your machine? Also, please include the source code for your Car class as well - just in case there may be an issue there.

I've included below, the complete source code which I used, and which seems to run correctly on my machine. The `main()` method is exactly as you provided except for the second last line, where I am assigning the result of `cache.remove()` to the `removed` variable.

It's entirely possible there may be a bug somewhere. But there is currently good test coverage (455 tests) for `TransactionalIndexedCollection` including for the `remove()` method. My main suspicion is that there might be an issue in your Car class or something. Maybe you could try executing my code below on your machine, and let me know how that goes. Thanks!

**My source code**
```java
package com.googlecode.cqengine;

import com.googlecode.cqengine.attribute.MultiValueAttribute;
import com.googlecode.cqengine.attribute.SimpleAttribute;
import com.googlecode.cqengine.index.hash.HashIndex;
import com.googlecode.cqengine.index.navigable.NavigableIndex;
import com.googlecode.cqengine.index.radixreversed.ReversedRadixTreeIndex;
import com.googlecode.cqengine.index.suffix.SuffixTreeIndex;
import com.googlecode.cqengine.query.option.QueryOptions;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class TransactionalIndexedCollectionRemoveTest {
    public static class Car {

        public static final SimpleAttribute<Car, Integer> CAR_ID = new SimpleAttribute<Car, Integer>("carId") {
            public Integer getValue(Car car, QueryOptions queryOptions) { return car.carId; }
        };

        public static final SimpleAttribute<Car, String> MANUFACTURER = new SimpleAttribute<Car, String>("manufacturer") {
            public String getValue(Car car, QueryOptions queryOptions) { return car.manufacturer; }
        };

        public static final SimpleAttribute<Car, String> MODEL = new SimpleAttribute<Car, String>("model") {
            public String getValue(Car car, QueryOptions queryOptions) { return car.model; }
        };

        public static final SimpleAttribute<Car, Car.Color> COLOR = new SimpleAttribute<Car, Car.Color>("color") {
            public Car.Color getValue(Car car, QueryOptions queryOptions) { return car.color; }
        };

        public static final SimpleAttribute<Car, Integer> DOORS = new SimpleAttribute<Car, Integer>("doors") {
            public Integer getValue(Car car, QueryOptions queryOptions) { return car.doors; }
        };

        public static final SimpleAttribute<Car, Double> PRICE = new SimpleAttribute<Car, Double>("price") {
            public Double getValue(Car car, QueryOptions queryOptions) { return car.price; }
        };

        public static final MultiValueAttribute<Car, String> FEATURES = new MultiValueAttribute<Car, String>("features") {
            public Iterable<String> getValues(Car car, QueryOptions queryOptions) { return car.features; }
        };

        public enum Color {RED, GREEN, BLUE, BLACK, WHITE}
        final int carId;
        final String manufacturer;
        final String model;
        final Car.Color color;
        final int doors;
        final double price;
        final List<String> features;
        final List<String> keywords;

        static final AtomicLong VERSION_GENERATOR = new AtomicLong();
        final long version = VERSION_GENERATOR.incrementAndGet();


        public Car(int carId, String manufacturer, String model, Car.Color color, int doors, double price, List<String> features, List<String> keywords) {
            this.carId = carId;
            this.manufacturer = manufacturer;
            this.model = model;
            this.color = color;
            this.doors = doors;
            this.price = price;
            this.features = features;
            this.keywords = keywords;
        }

        public int getCarId() {
            return carId;
        }

        public String getManufacturer() {
            return manufacturer;
        }

        public String getModel() {
            return model;
        }

        public Car.Color getColor() {
            return color;
        }

        public int getDoors() {
            return doors;
        }

        public double getPrice() {
            return price;
        }

        public List<String> getFeatures() {
            return features;
        }

        @Override
        public String toString() {
            return "Car{" +
                    "carId=" + carId +
                    ", manufacturer='" + manufacturer + '\'' +
                    ", model='" + model + '\'' +
                    ", color=" + color +
                    ", doors=" + doors +
                    ", price=" + price +
                    ", features=" + features +
                    ", keywords=" + keywords +
                    '}';
        }

        @Override
        public boolean equals(Object o) {
            if (this == o)
                return true;
            if (!(o instanceof Car))
                return false;
            Car car = (Car) o;
            if (carId != car.carId)
                return false;
            if (this.version != car.version)
                return false;
            return true;
        }

        @Override
        public int hashCode() {
            return carId;
        }
    }


    public static void main(String[] args) {
        TransactionalIndexedCollection<Car> cache = new TransactionalIndexedCollection<>(Car.class);

        cache.addIndex(NavigableIndex.onAttribute(Car.CAR_ID)); // SimpleAttribute
        cache.addIndex(ReversedRadixTreeIndex.onAttribute(Car.MANUFACTURER));
        cache.addIndex(SuffixTreeIndex.onAttribute(Car.MODEL));
        cache.addIndex(HashIndex.onAttribute(Car.FEATURES)); // MultiValueAttribute (features: List<String>)

        // new Car(int carId, String manufacturer, String model, Color color, int doors,
        // double price, List<String> features, List<String> keywords)
        Car car1 = new Car(1, "FORD", "ford focus", Car.Color.BLACK, 2, 10000.00d,
                Arrays.asList("spare tyre", "sunroof"), Arrays.asList("great condition, low mileage"));
        cache.add(car1);
        cache.add(new Car(2, "FORD", "ford taurus", Car.Color.BLUE, 4, 40000d, Arrays.asList("spare tyre", "radio"),
                Arrays.asList("dirty and unreliable, flat tyre")));
        cache.add(new Car(3, "HONDA", "honda civic", Car.Color.RED, 4, 10100d, Arrays.asList("radio"),
                Arrays.asList("has a flat tyre and high mileage")));
        System.out.println("Removing car with same attribs different (atomic) version");
        boolean removed = cache.remove(new Car(1, "FORD", "ford focus", Car.Color.BLACK, 2, 10000.00d,
                Arrays.asList("spare tyre", "sunroof"), Arrays.asList("great condition, low mileage")));
        System.out.println("Removed :" + removed);

        System.out.println("Removing with reference of original car1");
        removed = cache.remove(car1);
        System.out.println("Removed :" + removed);
    }
}
```

**Output**

```
Removing car with same attribs different (atomic) version
Removed :false
Removing with reference of original car1
Removed :true
```

**Comment by npgall** [comment] 2020-03-29 16:13
I will close this for now. If you still experience the problem, please reopen. Thanks!

**Closed by npgall** 2020-03-29 16:13 UTC
