### ISSUE TITLE
can't get it to work! / am I using this right?

### ISSUE THREAD

**Issue by joshualibrarian** [npgall/cqengine#187] opened 2018-02-14 18:44 UTC
So I'm trying to store a very large number (a million, say) of objects (the object is called **Item**), and I've already got a whole mechanism for storing them on disk, but I don't want to have them all in memory, so I'm trying to create an index with a path (and offset) to where exactly the Item itself is, and a couple other attributes of it as well, and each has a totally unique address that can be used as a sort of primary key.  Then I lookup the Entry and if it's actual Item member is null, then go fetch it from the disk using the path and offset, update the Entry and the indexes are un-effected unless one of its stored fields changes, right?  Also, it would be really nice if these indexes could persist so I don't have to create them every time the program loads, and the indexes could be maintained and only the Items actually needed could be fetched from the disk.  So I thought this cqengine looked perfect!  No?  I have it all structured, but I can't seem to get even simple queries to work, and the file that I eventually got it to create doesn't look like an actual index of the data at all, there's tens of thousands of items.  The docs would be better with more discussion of in what kinds of scenarios the different Indexes and Options and such would be used, like which *Index object is appropriate when.  Maybe I just need a bunch of maps to a common index String instead of all this?

Here is the object that should get indexed, an **Entry**:

```
public class Entry {
	
	private String address;
	protected String address() { return address; }
	protected void address(String address) { this.address = address; }
	
	private long order;
	protected long order() { return offset; } 
	protected void order(long offset) { this.offset = offset; }
	
	private String path;
	protected String path() { return path; } 
	protected void path(String path) { this.path = path; }

	private long offset;
	protected long offset() { return offset; } 
	protected void offset(long offset) { this.offset = offset; }

	private String clazz;
	protected String clazz() { return clazz; } 
	protected void clazz(String clazz) { this.clazz = clazz; }
	
	private Item item = null;
	protected Item item() { return item; } 
	protected void item(Item item) { this.item = item; }	
	
	protected Entry(Item item, Path path, long offset) {
		this.item = item;
		this.address = item.address().toString();
		this.clazz = item.getClass().getName();
		this.path = path.toString();
		this.offset = offset;
	}
	
	protected Entry(String address, String clazz, String path, long offset) {
		this.address = address;
		this.clazz = clazz;
		this.path = path;
		this.offset = offset;
	}
	
	public static SimpleAttribute<Entry, String> ADDRESS = new SimpleAttribute<Entry, String>() {
		@Override
		public String getValue(Entry context, QueryOptions queryOptions) {
			return context.address().toString();
		}
	};
	
	public static Attribute<Entry, String> CLASS = new SimpleAttribute<Entry, String>() {
		@Override
		public String getValue(Entry context, QueryOptions queryOptions) {
			return context.getClass().getName();
		}
	};
	
	public static final SimpleNullableAttribute<Entry, String> PATH = new SimpleNullableAttribute<Entry, String>() {
		@Override
		public String getValue(Entry context, QueryOptions queryOptions) {
			return context.path();
		}
	};
	
	public static SimpleNullableAttribute<Entry, Long> OFFSET = new SimpleNullableAttribute<Entry, Long>() {
		@Override
		public Long getValue(Entry context, QueryOptions queryOptions) {
			return context.offset();
		}
	};
	
}
```

And the object to manage this whole thing is an Index:

```
 public class Index {

	ConcurrentIndexedCollection<Entry> index;
	
	Path path;
	
	public Index(Path path) {
		this.path = path;
		index = new ConcurrentIndexedCollection<>(DiskPersistence.onPrimaryKeyInFile(Entry.ADDRESS, new File("test.index")));
		index.addIndex(UniqueIndex.onAttribute(Entry.ADDRESS));
		index.addIndex(HashIndex.onAttribute(Entry.CLASS));
		index.addIndex(HashIndex.onAttribute(Entry.PATH));
		index.addIndex(HashIndex.onAttribute(Entry.OFFSET));
	}
	
	public ArrayList<Entry> get(String address) {
		
		ArrayList<Entry> el = new ArrayList<>();
		try (ResultSet<Entry> results = index.retrieve(equal(Entry.ADDRESS, address))) {
			results.forEach(el::add);
			
		}
		return el;
	}
	
	public ArrayList<Entry> get(Class clazz) {
		ArrayList<Entry> el = new ArrayList<>();
		try (ResultSet<Entry> results = index.retrieve(equal(Entry.CLASS, clazz.getName()))) {
			results.forEach(el::add);
		}
		return el;
	}
	
	public Entry add(Item item, Path path, long offset) throws DuplicateException {
		Entry entry = new Entry(item, path, offset);
		System.out.println("Index.add(): adding entry: " + entry.address());
		index.add(entry);
		return entry;
		
	}

	public boolean contains(Entry entry) {
		return index.contains(entry);
	}
	
	public long size() {
		return index.size();
	}
	
}

```

I've been through a lot of iterations of all this, I considered keeping the actual Item objects separately in a ConcurrentHashMap and just using their address (String) fields as unique indexes...  Any suggestions are appreciated, I really want to get it to work right.  Thanks!

**Comment by npgall** [comment] 2018-02-14 19:54
It's a bit confusing that you're calling the collection an index. The collection contains all of the objects and all of the indexes, and if you use DiskPersistence, everything will be persisted to a single file.

If you want to store everything on disk then you should use DiskPersistence, and use only DiskIndexes. 

It looks like you are using HashIndex above. This type of index will not be stored on disk. You should use DiskIndex instead. Hope that helps.

**Comment by joshualibrarian** [comment] 2018-02-15 01:05
I had tried using UniqueIndex as well, since the address attribute is indeed unique like a primary key.  Okay, my confusing name choice aside, when I change it to all DiskIndexes, like this:

```
index = new ConcurrentIndexedCollection<>(DiskPersistence.onPrimaryKey(Entry.ADDRESS));
		index.addIndex(DiskIndex.onAttribute(Entry.ADDRESS));
		index.addIndex(DiskIndex.onAttribute(Entry.CLASS));
		index.addIndex(DiskIndex.onAttribute(Entry.PATH));
		index.addIndex(DiskIndex.onAttribute(Entry.OFFSET));
```

And now instead of just no results (when there should be), I get this exception:

```
Exception in thread "main" java.lang.IllegalStateException: An identity index for persistence has already been added, and no additional non-heap indexes are allowed, on attribute: Attribute{objectType=class org.sharingcreatesabundance.library.Entry, attributeType=class java.lang.String, attributeName='<Unnamed attribute, class org.sharingcreatesabundance.library.Entry$1>'}
	at com.googlecode.cqengine.engine.CollectionQueryEngine.addAttributeIndex(CollectionQueryEngine.java:184)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.addIndex(CollectionQueryEngine.java:160)
	at com.googlecode.cqengine.ConcurrentIndexedCollection.addIndex(ConcurrentIndexedCollection.java:173)
	at org.sharingcreatesabundance.library.Index.<init>(Index.java:30)
```

So not all DiskIndexes?  Is there another Index type appropriate for integers and such?

**Comment by npgall** [comment] 2018-02-15 01:51
Sorry my earlier response was a bit rushed. I agree it would be beneficial to add an example or more documentation for storing everything (objects + indexes) on disk and acessing it later.

*Additionally*, the wording of that new exception you got should be improved. So apologies for all of this confusion :(

You can fix the issue above by removing the line: 
`index.addIndex(DiskIndex.onAttribute(Entry.ADDRESS));`

Basically that exception means there was an attempt to add a duplicate index, on the attribute which was configured as the primary key for use with DiskPersistence. When you configure the collection itself to persist to disk, a DiskIndex on the primary key will be created *implicitly*. So there is no need to add a DiskIndex on the primary key explicitly, and this exception will be thrown if the application tries to do that.

Apart from that, I'd suggest to configure the persistence via [DiskPersistence.onPrimaryKeyInFile()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/disk/DiskPersistence.html#onPrimaryKeyInFile-com.googlecode.cqengine.attribute.SimpleAttribute-java.io.File-), rather than `DiskPersistence.onPrimaryKey()`, in order to store the collection + indexes in a particular, non-temp file on disk, so you can access the same persisted collection + indexes later. Because if you don't specify a particular File explicitly,  everything will be saved in a temp file which will be harder to access later.

What you want to do is supported. Hope that helps and please let me know if you still have issues!

**Comment by joshualibrarian** [comment] 2018-02-17 20:44
Okay, I got it to work!

I really appreciate your help!  In the configuration shown, I kept getting no results, no matter what query I tried... I solved it by simplifying my architecture a bit, I removed `Item` from the `Entry` entirely.  Now it JUST stores simple values (String and Long), with only the unique address of the `Item`, the class (as `String`) the file path  (also as `String`) and the offset.  Now it works beautifully!

Now I'm keeping the actual `Item` objects in a simple `ConcurrentHashMap<Item>` (loadedItems), so then when I query the "index" and get results, I just check each one in the loadedItems map and if it's not there then it hasn't been loaded into memory, so I use the path and offset to fetch it.  That all now works perfectly.  Thank you so much for your guidance!

And now, if I may, I'd like to ask for one other piece of guidance on using these excellent collections of yours!  So these `Item` objects of mine can generate "searchTerms" for each object, and I've build a "trie" to store them... and I'd really like to convert it to this system, to get it to store itself on disk like the other one did... but it's a complex little bugger full of collections, and I wanted to ask how viable you think that notion is... here is the class as it is now:

```
public class Trie {
    Node root;
    long size = 0;

    public Trie() {
    		root = new Node('\u0000');
    }
    
    public void add(Item item) {
    		Node currentNode = root;
    		ArrayList<String> terms = item.searchTerms();
    		if (terms != null) {
	    		for (String word : terms) {
	
	    			for (int d = 0; d < word.length(); d++) {
		    			HashMap<Integer, Node> children = currentNode.children();
		    			int c = word.codePointAt(d);
		    			
		    			if (children.containsKey(c)) {
		    				currentNode = children.get(c);
		    				
		    			} else {
		    				Node n = new Node(c);
		    				children.put(c,  n);
		    				currentNode = n;
		    			}
		    		}
		    		
		    		currentNode.data(item.address().toString());
	    		}
    		}	
    	}
    
    public ArrayList<String> get(String word) {
    		ArrayList<String> results = new ArrayList<>();
        
    		Node currentNode = root;
        int depth;
        
        for (depth = 0; depth < word.length(); depth++) {
            int c = word.codePointAt(depth);
            Node n = currentNode.children().get(c);
            if (n == null) {
            		break;
            }
            currentNode = n;
        }

        if (currentNode.data() != null ) {
        		results.addAll(currentNode.data());
        }
        	
        return results;
    }

    public long size() {
    		return size;
    }
    
    private class Node {
    		private int character;
    		private HashMap<Integer, Node> children;
    		private ArrayList<String> data;

    		protected HashMap<Integer, Node> children() { 
    			if (children == null) {
    				children = new HashMap<Integer, Node>();
    			}
    			return children;
    		}

    		protected ArrayList<String> data() { return data; }
    		protected void data(String stringValue) { 
    			if (data == null) {
    				data = new ArrayList<String>();
    			}
			size++;	//todo: this is unsustainable, how better to keep the size?
    			data.add(stringValue);
    		}

    		protected Node(int character) {
			this.character = character;
		}
    }
}
```

So what do you think?  Can this library handle something like this?

**Comment by joshualibrarian** [comment] 2018-02-19 21:56
Well, I'm giving it a good try at least, that is a lot of recursive ConcurrentIndexedCollections, but we'll see.  I got the whole thing put together and there is one last line that won't compile, and I just can't see to why.  It likes it for the `ArrayList<String>`, but not for the `ConcurrentIndexedCollection<TrieNode>` children.  Is this even possible?  Shown here is the relevant bits of the recursive ItemNode:  The function to fetch the child nodes and creates them if they are null.  Is there a NullableMultiMultiAttribute?  ;)

This is the line that the compiler won't take:
`			children.addIndex(DiskIndex.onAttribute(TrieNode.CHILDREN));
`

The compiler error is:
`The method onAttribute(Attribute<O,A>) in the type DiskIndex is not applicable for the arguments (MultiValueAttribute<TrieNode,TrieNode>)	TrieNode.java`

```
public class TrieNode {
	// ...
	protected ConcurrentIndexedCollection<TrieNode> children() { 
		if (children == null) {
			children = new ConcurrentIndexedCollection<TrieNode>(
				DiskPersistence.onPrimaryKeyInFile(TrieNode.CHARACTER, new File("trie.index")));
				children.addIndex(DiskIndex.onAttribute(TrieNode.CHILDREN));
				children.addIndex(DiskIndex.onAttribute(TrieNode.VALUES));
		}	
		return children;
	}
	// ...
}
```

Here are the static function that accompanies that index:

```
public static final MultiValueAttribute<TrieNode, TrieNode> CHILDREN = new MultiValueAttribute<TrieNode, TrieNode>("children") {
	@Override
	public Iterable<TrieNode> getValues(TrieNode node, QueryOptions queryOptions) {
		return node.children();
	}
};

```

Any help is appreciated, even telling me to abandon this approach!  Thanks!

**Comment by npgall** [comment] 2019-06-07 21:47
I've improved the message of that exception thrown when an attempt is made to add a duplicate index on the primary key attribute. I've also improved the documentation on this. Hopefully it will be less confusing in future.

However apart from that, I am not sure what issue you are running into. Are you still having the problem? The code you've posted above is pretty complicated and application-specific.

If you'd like me to investigate an issue, could you make a smaller self-contained test case which reproduces the problem? I will close this issue for now. Feel free to reopen if you still have the issue and could provide a smaller test case. Thanks!

**Closed by npgall** 2019-06-07 21:47 UTC
