### ISSUE TITLE
recommended way to perform an update in an IndexedCollection

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#132] opened 2017-04-04 11:14 UTC
Is it best to just use `.remove(foo)` then `.add(newFoo)`? What's the recommended approach for updates?

**Comment by npgall** [comment] 2017-04-27 20:51
Duplicate of https://github.com/npgall/cqengine/issues/133

**Closed by npgall** 2017-04-27 20:51 UTC

**Comment by bluedoo** [comment] 2017-05-04 12:43
Here is an example of the recommended approach:

https://github.com/npgall/cqengine/blob/master/code/src/test/java/com/googlecode/cqengine/examples/replace/Replace.java
