### ISSUE TITLE
iterator() idempotency for descendants of WrappedResultSet?

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine#78] opened 2016-07-13 03:32 UTC
When a wrapping result set is used, if `iterator()` returns a new value every time, there are undesirable consequences.

(For example, here: https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/resultset/order/MaterializedOrderedResultSet.java#L74 a new iterator will be returned every time)

It becomes a problem in scenarios like this:

```java
if (resultSet.isNotEmpty()) {
  return resultSet.iterator().next();
}
```

`ResultSet#isNotEmpty()` will do this `iterator().hasNext()`, creating a new iterator. In cases like `MaterializedOrderedResultSet.java` the wrapped iterator will be fully consumed. Now, when `resultSet.iterator()` is called, it will attempt to create a new wrapping iterator and read a fully "consumed" iterator again.

Proposed solution: in cases like this, instantiate only one copy of iterator, thus it will attempt to consume the wrapped iterator only once.

Thoughts?

**Comment by npgall** [comment] 2016-07-13 15:38
Whereabouts in the code is an `Iterator` wrapped? AFAIK, ResultSets should wrap an `Iterable` as opposed to an `Iterator` in most cases (and probably it should be all cases).

Calling Iterable.iterator() should then allow it to create a new iterator multiple times, each of which will restart iteration from the beginning of the results each time.

**Comment by yrashk** [comment] 2016-07-13 18:00
You are right. `ResultSet` does wrap an iterable and the problem I've experienced comes from an unfortunate optimization (aka mistake) I've done to my own index that creates own subclasses of `ResultSet`.

The optimization is based around the issue of having to incur an expense to create a new iterator over a JDBC query, meaning executing a new request every time a new iterator is created. So this is obviously going against expectations of `Iterable#iterator()`:

https://github.com/eventsourcing/es4j/blob/master/eventsourcing-postgresql/src/main/java/com/eventsourcing/postgresql/index/PostgreSQLAttributeIndex.java#L486-L506

I am going to fix this on my end. 

However, this still doesn't alleviate the issue with a performance penalty. If (or, rather, when) I fix the behaviour of my own `ResultSet`, both calling `isEmpty()` and `ResultSet#iterator()` through the wrapping `ResultSet` will initiate a query, which is what I'd rather avoid doing.

Right now I am avoiding the whole issue by fetching just one `iterator()` off the materializing ResultSet so it only materializes once. This will also help to avoid hitting the query twice when I fix my own ResultSet to return a new iterator every time `iterator()` is called. But I can definitely see how natural it is to use `isEmpty()/isNotEmpty()` before working with an iterator.

Do you have any thoughts on how to keep the right semantics and not shoot oneself in the foot performance-wise?

**Comment by npgall** [comment] 2016-07-14 00:03
Hi Yuri,

Good question. It would be useful to improve this in general.

How about this class I just added?: [IteratorCachingResultSet](https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/resultset/common/IteratorCachingResultSet.java)

You could wrap the ResultSet which your index returns in this, and if I understand correctly, it should solve the problem.

FYI I released CQEngine 2.7.0 earlier (I've yet to update the release notes though). However this new class didn't make it into that release, but it will be included in the next release. In the meantime you can copy IteratorCachingResultSet directly into your app.

**Comment by yrashk** [comment] 2016-07-14 01:00
I think will do, I'll check soon. Thanks! I will let you know.

**Comment by yrashk** [comment] 2016-07-14 02:06
On the second thought, I am not so sure it will help.

If I wrap my ResultSet into one that caches the iterator, it'll help with not re-querying the database. However, if I use `isEmpty()` and `iterator()` from `MaterializedOrderedResultSet`, it'll still attempt to consume the cached iterator twice to materialize it. Am I missing anything?

**Comment by npgall** [comment] 2016-07-15 17:28
I think you are right. The problem is `MaterializedOrderedResultSet` which extends `WrappedResultSet`, does not override `isEmpty()`. And by default `isEmpty()` calls `iterator()`. Whereas it would be more efficient if overrode `isEmpty()`, and it delegated to the `isEmpty()` method on the wrapped ResultSet instead.

I will make this minor change for the next point release.

**Comment by yrashk** [comment] 2016-07-23 14:14
does c897dc2732a47fe9b1bed4ca094fbc4264c80c16 resolve this issue?

**Comment by npgall** [comment] 2016-07-25 22:31
Hi Yurii, yes I think it did. 
It was an improvement anyway. Can you re-test with the latest code in master?

**Comment by npgall** [comment] 2016-08-12 20:09
Closing this now, as CQEngine 2.7.1 has been released, and I think it fixes this issue. Please reopen if that's not the case

**Closed by npgall** 2016-08-12 20:09 UTC
