### ISSUE TITLE
Failed to deserialize object from index, object type enum

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#116] opened 2016-12-19 17:07 UTC
When attempting to save an object using `DiskPersistence` I get the following error:

`Caused by: com.esotericsoftware.kryo.KryoException: Invalid ordinal for enum "Type": 50`

My object contains a field which is an instance of an enum type. i.e.

```
public enum Type {
   blue, 
   green
}

public class Person {
     public Type  type;
}
```

To reproduce simply call `add()` from a `ConcurrentIndexedCollection` and then `.retrieve(equal(selfAttribute(Foo.class), foo)).uniqueResult();`

**Comment by npgall** [comment] 2016-12-19 18:05
Can you provide a complete example (Test case, or class with main method) which I can run?

**Comment by bluedoo** [comment] 2016-12-20 15:05
I tried my best to simplify it into a focused class to reproduce the issue as simply as possible, see https://gist.github.com/bluedoo/f6e194b1425de93c724de639f137e7c0

**Comment by bluedoo** [comment] 2017-01-03 13:36
Did you manage to reproduce the issue?

**Comment by npgall** [comment] 2017-01-18 21:29
Hi @bluedoo, I think you'll need to simplify the test case.

In your test case you are supplying complex object graphs to CQEngine instead of POJOs, which are more typical. These object graphs are causing an exception during deserialization.

I can reproduce the exception when I run your test case, but there's so much complexity there, it would be too much work for me to isolate the particular aspect of your object graph which is causing the problem. Can you provide a simpler example which demonstrates the problem?

CQEngine uses [Kryo](https://github.com/EsotericSoftware/kryo) to serialize objects, and this exception means CQEngine/Kryo was able to serialize your object graphs, but it was unable to deserialize them later.

Here are some potential workarounds:
1. If you could simplify your objects if possible, to be more POJO-like, then it might not trigger this issue in Kryo.
2. You could add `@Bind(JavaSerializer.class)`/`@BindCollection`/`@BindMap` annotations to your objects, to force Kryo to use Java's built-in serializer to serialize your objects, instead of Kryo's higher performance serializers. See Kryo's [class field annotations](https://github.com/EsotericSoftware/kryo#class-fields-annotations) for more details.

The issue could either be due to how CQEngine [configures Kryo](https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/index/sqlite/SQLiteIdentityIndex.java#L136), or it could be due to a bug in Kryo itself which is triggered by something in your object graph.

As it's quite specific to your object graphs, I'll need your help to investigate further.
Could you check yourself if you can serialize your object graphs with Kryo (independent of CQEngine)?

**Comment by bluedoo** [comment] 2017-02-03 12:45
Thanks @npgall 

With all due respect, I think you'll be in a better position to understand this issue and provide a fix than myself or any other user. Are you sure you can't do anything?

**Comment by npgall** [comment] 2017-04-28 00:27
Sorry I disagree. No serializer on earth will be able to serialize this object graph..

Issue 1: On [line 79](https://gist.github.com/bluedoo/f6e194b1425de93c724de639f137e7c0#file-test-L79) you are storing a different IndexedCollection in a field in the POJO you are trying to serialize(!). Kryo is designed to serialize POJOs, and certainly not such complex object graphs.

Issue 2: On [line 83](https://gist.github.com/bluedoo/f6e194b1425de93c724de639f137e7c0#file-test-L83) you are creating an IndexedCollection which is configured to use off-heap persistence, inside the constructor of a POJO which you are trying to serialize. Java serialziation would fail at this hurdle, because it does not invoke constructors during deserialization.

So I will close this ticket. You can use simpler POJOs instead of these compex object graphs.

**Closed by npgall** 2017-04-28 00:27 UTC
