### ISSUE TITLE
Suggestion: Generate attributes from existing class on classpath instead of throwing exception on AttributeBytecodeGenerator.createAttributes

### ISSUE THREAD

**Issue by jarey** [npgall/cqengine#141] opened 2017-05-08 07:16 UTC
When attempting to create attributes of a class by using AttributeBytecodeGenerator.createAttributes, the second time you try to create them, you would receive an exception indicating that the generated class used to create the attributes for the class already exists in the classpath. 

I think it would be better, instead of throwing an exception, to use the existing class on classpath for the attribute generation, and to return them.

Thanks for your time.

**Comment by npgall** [comment] 2017-05-29 23:47
Hi jarey,

I was not aware of this issue, thanks for reporting it.

I can confirm that I get the issue your reported. However I can't really find a better way to handle this than the current behaviour which is to throw an exception...

It's because the attribute class name alone does not uniquely identify the "signature" of the attribute which the application is trying to generate. By signature I mean a combination of the attribute class name AND the field or getter method it reads from.

For example, the API currently allows the application to generate an attribute called "foo" but which actually reads a value by calling getter method getBar(). So if the application had done this, and subsequently tried to generate a different attribute with the same name again but which read from getBaz(), then it would not be safe to return the first attribute again, because it would silently call the wrong getter method.

So I'll close this issue for now as the current behavior seems the safer option. Feel free to reopen if you can think of another solution. 

In the meantime, the best solution would be for your application to keep track of the attributes it generates so as not to try to generate the same attribute more than once. Hope that helps!

**Closed by npgall** 2017-05-29 23:47 UTC
